// <auto-generated />
namespace UserApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewColumnAdded_04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumnAdded_04));
        
        string IMigrationMetadata.Id
        {
            get { return "202108250107286_NewColumnAdded_04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
